"""
Plot pretraining loss comparison between sliding window and non-sliding window
Loads data from JSON file (generated by parsing log files)
Generates two separate figures: tst1_loss_comparison and tst2_loss_comparison
"""
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend
import matplotlib.pyplot as plt
import numpy as np
import json
import os

# Set up matplotlib for better quality
plt.rcParams['figure.dpi'] = 150
plt.rcParams['font.size'] = 10
plt.rcParams['axes.labelsize'] = 11
plt.rcParams['axes.titlesize'] = 12
plt.rcParams['legend.fontsize'] = 9


def main():
    output_dir = '/root/workplace/exp/TwoTST/results'
    
    # Load all data from JSON
    print("Loading data from JSON...")
    with open(f'{output_dir}/pretrain_losses.json', 'r') as f:
        data = json.load(f)
    
    epochs = np.arange(1, 101)
    
    # ============================================================
    # Figure 1: TST1 Loss Comparison
    # ============================================================
    print("Generating TST1 figure...")
    fig1, axes1 = plt.subplots(1, 2, figsize=(12, 4.5))
    
    # TST1 Training Loss
    ax = axes1[0]
    ax.plot(epochs, data['sw_tst1_train'], label='With Sliding Window (4,815 samples)', 
            color='#2ecc71', linewidth=2)
    ax.plot(epochs, data['nosw_tst1_train'], label='Without Sliding Window (963 samples)', 
            color='#e74c3c', linewidth=2, linestyle='--')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('MSE Loss')
    ax.set_title('(a) TST1 Training Loss')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)
    ax.set_xlim([1, 100])
    
    # TST1 Validation Loss
    ax = axes1[1]
    ax.plot(epochs, data['sw_tst1_val'], label='With Sliding Window (4,815 samples)', 
            color='#2ecc71', linewidth=2)
    ax.plot(epochs, data['nosw_tst1_val'], label='Without Sliding Window (963 samples)', 
            color='#e74c3c', linewidth=2, linestyle='--')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('MSE Loss')
    ax.set_title('(b) TST1 Validation Loss')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)
    ax.set_xlim([1, 100])
    
    plt.tight_layout()
    plt.savefig(f'{output_dir}/tst1_loss_comparison.png', dpi=300, bbox_inches='tight')
    plt.savefig(f'{output_dir}/tst1_loss_comparison.pdf', bbox_inches='tight')
    print('Saved: tst1_loss_comparison.png')
    plt.close(fig1)
    
    # ============================================================
    # Figure 2: TST2 Loss Comparison
    # ============================================================
    print("Generating TST2 figure...")
    fig2, axes2 = plt.subplots(1, 2, figsize=(12, 4.5))
    
    # TST2 Training Loss
    ax = axes2[0]
    ax.plot(epochs, data['sw_tst2_train'], label='With Sliding Window (4,815 samples)', 
            color='#3498db', linewidth=2)
    ax.plot(epochs, data['nosw_tst2_train'], label='Without Sliding Window (963 samples)', 
            color='#9b59b6', linewidth=2, linestyle='--')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('MSE Loss')
    ax.set_title('(a) TST2 Training Loss')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)
    ax.set_xlim([1, 100])
    
    # TST2 Validation Loss
    ax = axes2[1]
    ax.plot(epochs, data['sw_tst2_val'], label='With Sliding Window (4,815 samples)', 
            color='#3498db', linewidth=2)
    ax.plot(epochs, data['nosw_tst2_val'], label='Without Sliding Window (963 samples)', 
            color='#9b59b6', linewidth=2, linestyle='--')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('MSE Loss')
    ax.set_title('(b) TST2 Validation Loss')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)
    ax.set_xlim([1, 100])
    
    plt.tight_layout()
    plt.savefig(f'{output_dir}/tst2_loss_comparison.png', dpi=300, bbox_inches='tight')
    plt.savefig(f'{output_dir}/tst2_loss_comparison.pdf', bbox_inches='tight')
    print('Saved: tst2_loss_comparison.png')
    plt.close(fig2)
    
    # ============================================================
    # Print Summary Statistics
    # ============================================================
    print("\n" + "=" * 60)
    print("TST1 Pre-training Summary")
    print("=" * 60)
    print(f"With Sliding Window:")
    print(f"  - Final Train Loss: {data['sw_tst1_train'][-1]:.4f}")
    print(f"  - Final Val Loss: {data['sw_tst1_val'][-1]:.4f}")
    print(f"  - Best Val Loss: {min(data['sw_tst1_val']):.4f} (Epoch {np.argmin(data['sw_tst1_val'])+1})")
    print(f"Without Sliding Window:")
    print(f"  - Final Train Loss: {data['nosw_tst1_train'][-1]:.4f}")
    print(f"  - Final Val Loss: {data['nosw_tst1_val'][-1]:.4f}")
    print(f"  - Best Val Loss: {min(data['nosw_tst1_val']):.4f} (Epoch {np.argmin(data['nosw_tst1_val'])+1})")
    
    print("\n" + "=" * 60)
    print("TST2 Pre-training Summary")
    print("=" * 60)
    print(f"With Sliding Window:")
    print(f"  - Final Train Loss: {data['sw_tst2_train'][-1]:.4f}")
    print(f"  - Final Val Loss: {data['sw_tst2_val'][-1]:.4f}")
    print(f"  - Best Val Loss: {min(data['sw_tst2_val']):.4f} (Epoch {np.argmin(data['sw_tst2_val'])+1})")
    print(f"Without Sliding Window:")
    print(f"  - Final Train Loss: {data['nosw_tst2_train'][-1]:.4f}")
    print(f"  - Final Val Loss: {data['nosw_tst2_val'][-1]:.4f}")
    print(f"  - Best Val Loss: {min(data['nosw_tst2_val']):.4f} (Epoch {np.argmin(data['nosw_tst2_val'])+1})")


if __name__ == '__main__':
    main()
